"""File documentation generator."""

from datetime import datetime
from pathlib import Path

from maikdocs.parsers.base import ParsedClass, ParsedFunction, ParsedModule


class FileDocumentationGenerator:
    """Generates markdown documentation for individual source files."""

    def generate(self, parsed: ParsedModule, output_path: Path) -> None:
        """Generate filename_maik.md for a source file.

        Args:
            parsed: Parsed module structure
            output_path: Path where to write documentation
        """
        output_path.parent.mkdir(parents=True, exist_ok=True)

        sections = []

        sections.append(self._generate_header(parsed))

        if parsed.docstring_summary:
            sections.append(self._generate_module_section(parsed))

        if parsed.classes:
            sections.append(self._generate_classes_section(parsed.classes))

        if parsed.functions:
            sections.append(self._generate_functions_section(parsed.functions))

        if parsed.constants:
            sections.append(self._generate_constants_section(parsed.constants))

        if parsed.attributes:
            sections.append(self._generate_attributes_section(parsed.attributes))

        content = "\n\n".join(sections)

        output_path.write_text(content + "\n", encoding="utf-8")

    def _generate_header(self, parsed: ParsedModule) -> str:
        """Generate header with file info.

        Args:
            parsed: Parsed module

        Returns:
            Header markdown
        """
        return f"# {parsed.path.name}\n\n*Auto-generated by maikdocs on {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}*"

    def _generate_module_section(self, parsed: ParsedModule) -> str:
        """Generate module documentation section.

        Args:
            parsed: Parsed module

        Returns:
            Module section markdown
        """
        lines = ["## Module"]

        if parsed.docstring_summary:
            lines.append(f"\n{parsed.docstring_summary}")

        exports = parsed.get_public_exports()
        if exports:
            lines.append(f"\n**Public exports:** {', '.join(f'`{e}`' for e in exports)}")

        return "\n".join(lines)

    def _generate_classes_section(self, classes: list[ParsedClass]) -> str:
        """Generate classes documentation section.

        Args:
            classes: List of parsed classes

        Returns:
            Classes section markdown
        """
        lines = ["## Classes"]

        for cls in classes:
            lines.append(f"\n### `{cls.name}`")

            if cls.base_classes:
                bases = ", ".join(f"`{b}`" for b in cls.base_classes)
                lines.append(f"\nInherits from: {bases}")

            visibility_marker = "PRIVATE" if cls.visibility == "private" else "PUBLIC"
            lines.append(f"\nVisibility: {visibility_marker} {cls.visibility}")

            if cls.docstring_summary:
                lines.append(f"\n{cls.docstring_summary}")

            if cls.methods:
                lines.append("\n**Methods:**")
                for method in cls.methods:
                    vis_marker = "PRIVATE" if method.visibility == "private" else "PUBLIC"
                    sig = self._format_signature(method)
                    lines.append(f"- {vis_marker} `{sig}`")
                    if method.docstring_summary:
                        lines.append(f"  - {method.docstring_summary}")

            if cls.attributes:
                lines.append("\n**Attributes:**")
                for attr in cls.attributes:
                    vis_marker = "PRIVATE" if attr.visibility == "private" else "PUBLIC"
                    lines.append(f"- {vis_marker} `{attr.signature}`")
                    if attr.docstring_summary:
                        lines.append(f"  - {attr.docstring_summary}")

        return "\n".join(lines)

    def _generate_functions_section(self, functions: list[ParsedFunction]) -> str:
        """Generate functions documentation section.

        Args:
            functions: List of parsed functions

        Returns:
            Functions section markdown
        """
        lines = ["## Functions"]

        for func in functions:
            vis_marker = "PRIVATE" if func.visibility == "private" else "PUBLIC"
            sig = self._format_signature(func)
            lines.append(f"\n### {vis_marker} `{sig}`")

            if func.docstring_summary:
                lines.append(f"\n{func.docstring_summary}")

            if func.parameters:
                lines.append("\n**Parameters:**")
                for param in func.parameters:
                    param_str = f"`{param.name}`"
                    if param.type_hint:
                        param_str += f": `{param.type_hint}`"
                    if param.default_value:
                        param_str += f" = `{param.default_value}`"
                    lines.append(f"- {param_str}")

            if func.return_type:
                lines.append(f"\n**Returns:** `{func.return_type}`")

        return "\n".join(lines)

    def _generate_constants_section(self, constants: list) -> str:
        """Generate constants documentation section.

        Args:
            constants: List of parsed constants

        Returns:
            Constants section markdown
        """
        lines = ["## Constants"]

        for const in constants:
            vis_marker = "PRIVATE" if const.visibility == "private" else "PUBLIC"
            lines.append(f"\n### {vis_marker} `{const.name}`")

            if const.type_hint:
                lines.append(f"\nType: `{const.type_hint}`")

            if const.docstring_summary:
                lines.append(f"\n{const.docstring_summary}")

        return "\n".join(lines)

    def _generate_attributes_section(self, attributes: list) -> str:
        """Generate module attributes section.

        Args:
            attributes: List of parsed attributes

        Returns:
            Attributes section markdown
        """
        lines = ["## Module Attributes"]

        for attr in attributes:
            vis_marker = "PRIVATE" if attr.visibility == "private" else "PUBLIC"
            lines.append(f"\n### {vis_marker} `{attr.name}`")

            if attr.type_hint:
                lines.append(f"\nType: `{attr.type_hint}`")

            if attr.docstring_summary:
                lines.append(f"\n{attr.docstring_summary}")

        return "\n".join(lines)

    def _format_signature(self, func: ParsedFunction) -> str:
        """Format function signature for display.

        Args:
            func: Parsed function

        Returns:
            Formatted signature string
        """
        params = []
        for param in func.parameters:
            param_str = param.name
            if param.type_hint:
                param_str += f": {param.type_hint}"
            if param.default_value:
                param_str += f" = {param.default_value}"
            params.append(param_str)

        sig = f"{func.name}({', '.join(params)})"

        if func.return_type:
            sig += f" -> {func.return_type}"

        return sig
