"""Index documentation generator for directories."""

from datetime import datetime
from pathlib import Path

from maikdocs.core.config import MaikDocsConfig
from maikdocs.parsers.base import ParsedModule


class IndexDocumentationGenerator:
    """Generates index_maik.md for directories."""

    def __init__(self, config: MaikDocsConfig) -> None:
        """Initialize generator with configuration.

        Args:
            config: Project configuration
        """
        self.config = config

    def generate(
        self,
        directory: Path,
        modules: list[ParsedModule],
    ) -> None:
        """Generate directory index.

        Args:
            directory: Directory path
            modules: Parsed modules in this directory
        """
        index_path = self.config.get_index_path(directory)
        index_path.parent.mkdir(parents=True, exist_ok=True)

        sections = []

        sections.append(self._generate_header(directory))

        meta_path = self.config.get_meta_path(directory)
        if meta_path.exists():
            sections.append(self._read_meta_file(meta_path))

        if modules:
            sections.append(self._generate_files_section(modules))

        content = "\n\n".join(sections)

        index_path.write_text(content + "\n", encoding="utf-8")

    def _generate_header(self, directory: Path) -> str:
        """Generate header for index.

        Args:
            directory: Directory path

        Returns:
            Header markdown
        """
        try:
            rel_path = directory.relative_to(self.config.project_root)
            title = str(rel_path) if str(rel_path) != "." else "Project Root"
        except ValueError:
            title = directory.name

        return f"# {title}\n\n*Directory index generated by maikdocs on {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}*"

    def _read_meta_file(self, meta_path: Path) -> str:
        """Read and include user-provided metadata.

        Args:
            meta_path: Path to .maik_meta.md

        Returns:
            Metadata content
        """
        return meta_path.read_text(encoding="utf-8").strip()

    def _generate_files_section(self, modules: list[ParsedModule]) -> str:
        """Generate files listing section.

        Args:
            modules: Parsed modules

        Returns:
            Files section markdown
        """
        lines = ["## Files"]

        for module in sorted(modules, key=lambda m: m.path.name):
            lines.append(f"\n### {module.path.name}")

            if module.docstring_summary:
                lines.append(f"\n{module.docstring_summary}")

            exports = module.get_public_exports()
            if exports:
                lines.append(f"\n**Public API:** {', '.join(f'`{e}`' for e in exports)}")

            loc = self._count_lines(module.path)
            mtime = module.path.stat().st_mtime
            mtime_str = datetime.fromtimestamp(mtime).strftime('%Y-%m-%d %H:%M:%S')

            lines.append(f"\n**Metadata:**")
            lines.append(f"- Lines of code: {loc}")
            lines.append(f"- Last modified: {mtime_str}")

        return "\n".join(lines)

    def _count_lines(self, path: Path) -> int:
        """Count lines of code in a file.

        Args:
            path: File path

        Returns:
            Number of lines
        """
        try:
            return len(path.read_text(encoding="utf-8").splitlines())
        except Exception:
            return 0
