"""Project-level documentation generator."""

from datetime import datetime
from pathlib import Path

from maikdocs.core.config import MaikDocsConfig
from maikdocs.parsers.base import ParsedModule


class ProjectDocumentationGenerator:
    """Generates high-level PROJECT.md for entire project."""

    def __init__(self, config: MaikDocsConfig) -> None:
        """Initialize generator with configuration.

        Args:
            config: Project configuration
        """
        self.config = config

    def generate(
        self,
        modules: list[ParsedModule],
        directories: set[Path],
    ) -> None:
        """Generate project-level overview.

        Args:
            modules: All parsed modules in project
            directories: All directories with source files
        """
        project_path = self.config.project_root / self.config.output_folder / "PROJECT.md"
        project_path.parent.mkdir(parents=True, exist_ok=True)

        sections = []

        sections.append(self._generate_header())

        sections.append(self._generate_overview(modules))

        sections.append(self._generate_structure(directories))

        sections.append(self._generate_modules(modules, directories))

        sections.append(self._generate_statistics(modules))

        content = "\n\n".join(sections)

        project_path.write_text(content + "\n", encoding="utf-8")

    def _generate_header(self) -> str:
        """Generate header.

        Returns:
            Header markdown
        """
        project_name = self.config.project_root.name
        return f"# {project_name}\n\n*Project documentation generated by maikdocs on {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}*"

    def _generate_overview(self, modules: list[ParsedModule]) -> str:
        """Generate project overview section.

        Args:
            modules: All parsed modules

        Returns:
            Overview markdown
        """
        lines = ["## Project Overview"]

        root_init = None
        for module in modules:
            if module.path.name == "__init__.py" and len(module.path.parts) <= 3:
                root_init = module
                break

        if root_init and root_init.docstring_summary:
            lines.append(f"\n{root_init.docstring_summary}")
        else:
            lines.append(f"\nProject root: `{self.config.project_root}`")

        lines.append(f"\n**Languages:** {', '.join(self.config.languages)}")
        lines.append(f"**Documentation folder:** `{self.config.output_folder}`")

        return "\n".join(lines)

    def _generate_structure(self, directories: set[Path]) -> str:
        """Generate project structure section.

        Args:
            directories: All directories with source files

        Returns:
            Structure markdown
        """
        lines = ["## Project Structure"]

        sorted_dirs = sorted(directories, key=lambda d: (len(d.parts), str(d)))

        tree_lines = []
        for directory in sorted_dirs[:20]:
            try:
                rel_path = directory.relative_to(self.config.project_root)
                depth = len(rel_path.parts) - 1
                indent = "  " * depth
                name = rel_path.parts[-1] if rel_path.parts else "."

                tree_lines.append(f"{indent}- `{name}/`")
            except ValueError:
                pass

        if tree_lines:
            lines.append("\n```")
            lines.extend(tree_lines)
            if len(sorted_dirs) > 20:
                lines.append(f"... and {len(sorted_dirs) - 20} more directories")
            lines.append("```")

        return "\n".join(lines)

    def _generate_modules(
        self,
        modules: list[ParsedModule],
        directories: set[Path]
    ) -> str:
        """Generate key modules section.

        Args:
            modules: All parsed modules
            directories: All directories

        Returns:
            Modules markdown
        """
        lines = ["## Key Modules"]

        dir_modules = {}
        for directory in sorted(directories, key=lambda d: len(d.parts)):
            dir_modules[directory] = []

        for module in modules:
            if module.path.parent in dir_modules:
                dir_modules[module.path.parent].append(module)

        for directory in sorted(directories, key=lambda d: len(d.parts))[:10]:
            try:
                rel_path = directory.relative_to(self.config.project_root)
                dir_name = str(rel_path) if str(rel_path) != "." else "root"

                mods = dir_modules.get(directory, [])
                if not mods:
                    continue

                lines.append(f"\n### `{dir_name}`")

                for module in sorted(mods, key=lambda m: m.path.name)[:5]:
                    if module.docstring_summary:
                        lines.append(f"- **{module.path.name}**: {module.docstring_summary}")
                    else:
                        exports = module.get_public_exports()
                        if exports:
                            lines.append(f"- **{module.path.name}**: Exports {', '.join(f'`{e}`' for e in exports[:3])}")

            except ValueError:
                pass

        return "\n".join(lines)

    def _generate_statistics(self, modules: list[ParsedModule]) -> str:
        """Generate statistics section.

        Args:
            modules: All parsed modules

        Returns:
            Statistics markdown
        """
        lines = ["## Project Statistics"]

        total_classes = sum(len(m.classes) for m in modules)
        total_functions = sum(len(m.functions) for m in modules)
        total_files = len(modules)

        public_classes = sum(
            len([c for c in m.classes if c.visibility == "public"])
            for m in modules
        )
        public_functions = sum(
            len([f for f in m.functions if f.visibility == "public"])
            for m in modules
        )

        lines.append(f"\n- **Total Files:** {total_files}")
        lines.append(f"- **Total Classes:** {total_classes} ({public_classes} public)")
        lines.append(f"- **Total Functions:** {total_functions} ({public_functions} public)")

        documented_modules = sum(1 for m in modules if m.docstring)
        lines.append(f"- **Documented Modules:** {documented_modules}/{total_files} ({(documented_modules/total_files*100):.1f}%)")

        return "\n".join(lines)
